language: node_js
node_js:
  - '10'
install:
  - npm ci --prefix firebase-demo-web
  - npm ci --prefix functions
jobs:
  include:
    - stage: Dev
      script:
        - npm run prebuild --prefix firebase-demo-web
        - npm run build.dev --prefix firebase-demo-web
      deploy:
        - provider: firebase
          skip_cleanup: true
          token:
            secure: $FIREBASE_TOKEN
    - stage: Prod
      if: tag IS present
      script:
        - npm run prebuild --prefix firebase-demo-web
        - npm run build.prod --prefix firebase-demo-web
      deploy:
        - provider: firebase
          skip_cleanup: true
          token:
            secure: $FIREBASE_TOKEN
          project: "fir-87d91"
          on:
            tags: true
