name: Build Check

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'

      - name: Install Dependencies
        run: |
          npm ci --prefix firebase-demo-web
          npm ci --prefix functions

      - name: Build
        if: success()
        run: |
          npm run lint --prefix firebase-demo-web
          npm run lint --prefix functions
          npm run prebuild --prefix firebase-demo-web
          npm run build.dev --prefix firebase-demo-web
          npm run build --prefix functions
