name: DEV

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm ci --prefix firebase-demo-web
          npm ci --prefix functions

      - name: Build
        if: success()
        run: |
          npm run prebuild --prefix firebase-demo-web
          npm run build.dev --prefix firebase-demo-web
          npm run build --prefix functions

      - name: Archive Artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: firebase-demo-web/dist

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm ci --prefix firebase-demo-web
          npm ci --prefix functions

      - name: Lint
        if: success()
        run: |
          npm run lint --prefix firebase-demo-web
          npm run lint --prefix functions

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm ci --prefix firebase-demo-web

#       - name: Test
#         if: success()
#         run: |
#           npm run test --prefix firebase-demo-web

  deploy:
    name: Deploy
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: firebase-demo-web/dist
      
      - name: Install Dependencies
        run: npm ci --prefix functions

      - name: Deploy to Firebase
        if: success()
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
